export const PANEL_SLOTS = [
  {
    value: 'top',
    label: 'Top',
    rowStart: 1,
    rowSpan: 1,
    columnStart: 1,
    columnSpan: 5,
    direction: 'horizontal',
  },
  {
    value: 'top-inner',
    label: 'Top Inner',
    rowStart: 2,
    rowSpan: 1,
    columnStart: 2,
    columnSpan: 3,
    direction: 'horizontal',
  },
  {
    value: 'left-outer',
    label: 'Left Outer',
    rowStart: 2,
    rowSpan: 4,
    columnStart: 1,
    columnSpan: 1,
    direction: 'vertical',
  },
  {
    value: 'left-inner',
    label: 'Left Inner',
    rowStart: 3,
    rowSpan: 1,
    columnStart: 2,
    columnSpan: 1,
    direction: 'vertical',
  },
  {
    value: 'center',
    label: 'Center',
    rowStart: 3,
    rowSpan: 1,
    columnStart: 3,
    columnSpan: 1,
    direction: 'vertical',
  },
  {
    value: 'right-inner',
    label: 'Right Inner',
    rowStart: 3,
    rowSpan: 1,
    columnStart: 4,
    columnSpan: 1,
    direction: 'vertical',
  },
  {
    value: 'right-outer',
    label: 'Right Outer',
    rowStart: 2,
    rowSpan: 4,
    columnStart: 5,
    columnSpan: 1,
    direction: 'vertical',
  },
  {
    value: 'bottom-inner',
    label: 'Bottom Inner',
    rowStart: 4,
    rowSpan: 1,
    columnStart: 2,
    columnSpan: 3,
    direction: 'horizontal',
  },
  {
    value: 'bottom',
    label: 'Bottom',
    rowStart: 5,
    rowSpan: 1,
    columnStart: 2,
    columnSpan: 3,
    direction: 'horizontal',
  },
] as const
